# golangci-lint configuration file
# This file configures golangci-lint for the anyproxy project

# Version of golangci-lint to use
version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - build
    - bin
  skip-files:
    - ".*\\.pb\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  misspell:
    locale: US
  lll:
    line-length: 140
  govet:
    check-shadowing: true
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
  gosec:
    severity: "low"
    confidence: "low"

linters:
  disable-all: true
  enable:
    # Default enabled linters (always good to have)
    - errcheck       # Check for unchecked errors
    - govet          # Standard go vet checks
    - ineffassign    # Detect ineffective assignments
    - staticcheck    # Comprehensive static analysis
    - unused         # Find unused code
    
    # Additional useful linters
    - misspell       # Check for misspelled words
    - revive         # Replacement for golint
    - gosec          # Security-focused linting
    - goconst        # Find repeated strings that could be constants 
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Find unused function parameters

issues:
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false 