# golangci-lint configuration file
# This file configures golangci-lint for the anyproxy project

version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false  # Don't analyze test files at all

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  misspell:
    locale: US
  lll:
    line-length: 140
  govet:
    enable:
      - shadow
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
      - name: unused-parameter
        severity: warning
        disabled: false
  gosec:
    severity: "low"
    confidence: "low"
  errcheck:
    # Only exclude truly safe functions
    exclude-functions:
      - io.Copy
      - io.WriteString
  unused:
    check-exported: false

linters:
  disable-all: true
  enable:
    # Default enabled linters (always good to have)
    - errcheck       # Check for unchecked errors
    - govet          # Standard go vet checks
    - ineffassign    # Detect ineffective assignments
    - staticcheck    # Comprehensive static analysis
    - unused         # Find unused code
    
    # Additional useful linters
    - misspell       # Check for misspelled words
    - revive         # Replacement for golint
    - gosec          # Security-focused linting
    - goconst        # Find repeated strings that could be constants 
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Find unused function parameters

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - build
    - bin
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_test\\.go$"  # Skip all test files
  uniq-by-line: true
  exclude-rules:
    # === ONLY EXCLUDE TEST FILES ===
    - path: "_test\\.go$"
      linters:
        - errcheck
        - unparam
        - gosec
        - unused
        - goconst
        - ineffassign
        - revive
        - staticcheck
        - govet
        - misspell
        - unconvert
    
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false 