# AnyProxy Basic Configuration
# Simple setup for HTTP/SOCKS5 proxy with WebSocket transport

log:
  level: "info"
  format: "text"
  output: "stdout"

transport:
  type: "websocket"

# Gateway (deployed on public server)
gateway:
  listen_addr: ":8443"
  tls_cert: "certs/server.crt"
  tls_key: "certs/server.key"
  auth_username: "gateway_admin"
  auth_password: "secure_password_2024"

# Proxy services
proxy:
  http:
    listen_addr: ":8080"
    auth_username: "http_user"
    auth_password: "http_password"
  socks5:
    listen_addr: ":1080"
    auth_username: "socks_user"
    auth_password: "socks_password"

# Client (deployed on private network)
client:
  gateway_addr: "YOUR_GATEWAY_IP:8443"
  gateway_tls_cert: "certs/server.crt"
  client_id: "home-client"
  group_id: "home"
  auth_username: "gateway_admin"
  auth_password: "secure_password_2024"
  
  # Security settings
  forbidden_hosts:
    - "169.254.0.0/16"        # Cloud metadata
    - "127.0.0.1"
    - "localhost"
  
  allowed_hosts:
    - "192.168.1.0/24:*"      # Local network
    - "*.local:*"             # Local services

# Usage examples:
# HTTP: curl -x http://http_user:http_password@YOUR_GATEWAY_IP:8080 https://httpbin.org/ip
# SOCKS5: curl --socks5 socks_user:socks_password@YOUR_GATEWAY_IP:1080 https://httpbin.org/ip 