# Clash for Android Simplified Configuration File
# Based on AnyProxy proxy server configuration

# Port configuration
port: 7890
socks-port: 7891
mixed-port: 7893

# Allow LAN connections
allow-lan: true

# Running mode: rule / global / direct
mode: rule

# Log level
log-level: info

# External controller
external-controller: 127.0.0.1:9090

# DNS configuration
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8

# Proxy server configuration
proxies:
  # HTTP proxy - modify to your actual server IP
  - name: "AnyProxy-HTTP"
    type: http
    server: 127.0.0.1  # Please modify to your actual server IP
    port: 8080
    username: user
    password: password

  # SOCKS5 proxy - modify to your actual server IP
  - name: "AnyProxy-SOCKS5"
    type: socks5
    server: 127.0.0.1  # Please modify to your actual server IP
    port: 1080
    # Note: Your SOCKS5 configuration has empty username and password, so no authentication is set here

# Proxy group configuration
proxy-groups:
  # Main proxy selection group
  - name: "Proxy Selection"
    type: select
    proxies:
      - "Auto Select"
      - "Direct Connection"
      - "AnyProxy-HTTP"
      - "AnyProxy-SOCKS5"

  # Auto selection group
  - name: "Auto Select"
    type: url-test
    proxies:
      - "AnyProxy-HTTP"
      - "AnyProxy-SOCKS5"
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  # Direct connection
  - name: "Direct Connection"
    type: select
    proxies:
      - DIRECT

# Rule configuration
rules:
  # Local network direct connection
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT

  # Chinese websites direct connection
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-SUFFIX,baidu.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,tmall.com,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT

  # Foreign websites use proxy
  - DOMAIN-SUFFIX,google.com,Proxy Selection
  - DOMAIN-SUFFIX,youtube.com,Proxy Selection
  - DOMAIN-SUFFIX,facebook.com,Proxy Selection
  - DOMAIN-SUFFIX,twitter.com,Proxy Selection
  - DOMAIN-SUFFIX,instagram.com,Proxy Selection
  - DOMAIN-SUFFIX,github.com,Proxy Selection

  # China IP direct connection
  - GEOIP,CN,DIRECT

  # Other traffic uses proxy
  - MATCH,Proxy Selection 