# Clash for Android Configuration File
# Based on AnyProxy proxy server configuration

# Port configuration
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893

# Allow LAN connections
allow-lan: true

# Bind address
bind-address: "*"

# Running mode: rule / global / direct
mode: rule

# Log level: info / warning / error / debug / silent
log-level: info

# External controller
external-controller: 127.0.0.1:9090

# External UI
external-ui: folder

# DNS configuration
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8
    - 1.1.1.1
  fallback:
    - 8.8.8.8
    - 1.1.1.1
    - tls://dns.rubyfish.cn:853
    - tls://1.0.0.1:853
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

# Proxy server configuration
proxies:
  # HTTP proxy
  - name: "AnyProxy-HTTP"
    type: http
    server: 127.0.0.1
    port: 8080
    username: user
    password: password
    # skip-cert-verify: false
    # tls: false

  # SOCKS5 proxy
  - name: "AnyProxy-SOCKS5"
    type: socks5
    server: 127.0.0.1
    port: 1080
    # username: ""
    # password: ""
    # udp: true

# Proxy group configuration
proxy-groups:
  # Main proxy selection group
  - name: "🚀 Proxy Selection"
    type: select
    proxies:
      - "♻️ Auto Select"
      - "🎯 Global Direct"
      - "AnyProxy-HTTP"
      - "AnyProxy-SOCKS5"

  # Auto selection group
  - name: "♻️ Auto Select"
    type: url-test
    proxies:
      - "AnyProxy-HTTP"
      - "AnyProxy-SOCKS5"
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  # Global direct
  - name: "🎯 Global Direct"
    type: select
    proxies:
      - DIRECT

  # Application routing
  - name: "📲 Telegram"
    type: select
    proxies:
      - "🚀 Proxy Selection"
      - "♻️ Auto Select"
      - "🎯 Global Direct"
      - "AnyProxy-HTTP"
      - "AnyProxy-SOCKS5"

  - name: "📹 YouTube"
    type: select
    proxies:
      - "🚀 Proxy Selection"
      - "♻️ Auto Select"
      - "🎯 Global Direct"
      - "AnyProxy-HTTP"
      - "AnyProxy-SOCKS5"

  - name: "🎵 NetEase Music"
    type: select
    proxies:
      - "🎯 Global Direct"
      - "🚀 Proxy Selection"
      - "♻️ Auto Select"

  - name: "🎮 Gaming Platform"
    type: select
    proxies:
      - "🎯 Global Direct"
      - "🚀 Proxy Selection"
      - "♻️ Auto Select"

  - name: "🍃 Ad Blocking"
    type: select
    proxies:
      - REJECT
      - DIRECT

  - name: "🐟 Final"
    type: select
    proxies:
      - "🚀 Proxy Selection"
      - "🎯 Global Direct"
      - "♻️ Auto Select"
      - "AnyProxy-HTTP"
      - "AnyProxy-SOCKS5"

# Rule configuration
rules:
  # Local network direct connection
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT

  # Ad blocking
  - DOMAIN-SUFFIX,googlesyndication.com,🍃 Ad Blocking
  - DOMAIN-SUFFIX,googleadservices.com,🍃 Ad Blocking
  - DOMAIN-SUFFIX,doubleclick.net,🍃 Ad Blocking
  - DOMAIN-SUFFIX,googletagmanager.com,🍃 Ad Blocking

  # Telegram
  - DOMAIN-SUFFIX,t.me,📲 Telegram
  - DOMAIN-SUFFIX,tdesktop.com,📲 Telegram
  - DOMAIN-SUFFIX,telegra.ph,📲 Telegram
  - DOMAIN-SUFFIX,telegram.me,📲 Telegram
  - DOMAIN-SUFFIX,telegram.org,📲 Telegram
  - IP-CIDR,91.108.4.0/22,📲 Telegram
  - IP-CIDR,91.108.8.0/22,📲 Telegram
  - IP-CIDR,91.108.12.0/22,📲 Telegram
  - IP-CIDR,91.108.16.0/22,📲 Telegram
  - IP-CIDR,91.108.56.0/22,📲 Telegram
  - IP-CIDR,149.154.160.0/20,📲 Telegram

  # YouTube
  - DOMAIN-SUFFIX,googlevideo.com,📹 YouTube
  - DOMAIN-SUFFIX,youtube.com,📹 YouTube
  - DOMAIN-SUFFIX,ytimg.com,📹 YouTube
  - DOMAIN-SUFFIX,youtu.be,📹 YouTube

  # NetEase Music
  - DOMAIN-SUFFIX,music.163.com,🎵 NetEase Music
  - DOMAIN-SUFFIX,163yun.com,🎵 NetEase Music

  # Gaming platforms
  - DOMAIN-SUFFIX,steam.com,🎮 Gaming Platform
  - DOMAIN-SUFFIX,steampowered.com,🎮 Gaming Platform
  - DOMAIN-SUFFIX,steamcommunity.com,🎮 Gaming Platform
  - DOMAIN-SUFFIX,steamstatic.com,🎮 Gaming Platform

  # Foreign services
  - DOMAIN-SUFFIX,google.com,🚀 Proxy Selection
  - DOMAIN-SUFFIX,googleapis.com,🚀 Proxy Selection
  - DOMAIN-SUFFIX,googleusercontent.com,🚀 Proxy Selection
  - DOMAIN-SUFFIX,gstatic.com,🚀 Proxy Selection
  - DOMAIN-SUFFIX,facebook.com,🚀 Proxy Selection
  - DOMAIN-SUFFIX,twitter.com,🚀 Proxy Selection
  - DOMAIN-SUFFIX,instagram.com,🚀 Proxy Selection
  - DOMAIN-SUFFIX,github.com,🚀 Proxy Selection
  - DOMAIN-SUFFIX,githubusercontent.com,🚀 Proxy Selection

  # Chinese websites direct connection
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-KEYWORD,-cn,DIRECT
  - DOMAIN-SUFFIX,126.com,DIRECT
  - DOMAIN-SUFFIX,163.com,DIRECT
  - DOMAIN-SUFFIX,360.com,DIRECT
  - DOMAIN-SUFFIX,alipay.com,DIRECT
  - DOMAIN-SUFFIX,amap.com,DIRECT
  - DOMAIN-SUFFIX,baidu.com,DIRECT
  - DOMAIN-SUFFIX,bdstatic.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,caiyunapp.com,DIRECT
  - DOMAIN-SUFFIX,clouddn.com,DIRECT
  - DOMAIN-SUFFIX,cnbeta.com,DIRECT
  - DOMAIN-SUFFIX,cnbetacdn.com,DIRECT
  - DOMAIN-SUFFIX,cootekservice.com,DIRECT
  - DOMAIN-SUFFIX,csdn.net,DIRECT
  - DOMAIN-SUFFIX,ctrip.com,DIRECT
  - DOMAIN-SUFFIX,douban.com,DIRECT
  - DOMAIN-SUFFIX,doubanio.com,DIRECT
  - DOMAIN-SUFFIX,duokan.com,DIRECT
  - DOMAIN-SUFFIX,easou.com,DIRECT
  - DOMAIN-SUFFIX,ele.me,DIRECT
  - DOMAIN-SUFFIX,feng.com,DIRECT
  - DOMAIN-SUFFIX,fir.im,DIRECT
  - DOMAIN-SUFFIX,frdic.com,DIRECT
  - DOMAIN-SUFFIX,g-cores.com,DIRECT
  - DOMAIN-SUFFIX,godic.net,DIRECT
  - DOMAIN-SUFFIX,gtimg.com,DIRECT
  - DOMAIN-SUFFIX,hongxiu.com,DIRECT
  - DOMAIN-SUFFIX,hxcdn.net,DIRECT
  - DOMAIN-SUFFIX,iciba.com,DIRECT
  - DOMAIN-SUFFIX,ifeng.com,DIRECT
  - DOMAIN-SUFFIX,ifengimg.com,DIRECT
  - DOMAIN-SUFFIX,ipip.net,DIRECT
  - DOMAIN-SUFFIX,iqiyi.com,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,jianshu.com,DIRECT
  - DOMAIN-SUFFIX,knewone.com,DIRECT
  - DOMAIN-SUFFIX,le.com,DIRECT
  - DOMAIN-SUFFIX,lecloud.com,DIRECT
  - DOMAIN-SUFFIX,lemicp.com,DIRECT
  - DOMAIN-SUFFIX,licdn.com,DIRECT
  - DOMAIN-SUFFIX,luoo.net,DIRECT
  - DOMAIN-SUFFIX,meituan.com,DIRECT
  - DOMAIN-SUFFIX,meituan.net,DIRECT
  - DOMAIN-SUFFIX,mi.com,DIRECT
  - DOMAIN-SUFFIX,miaopai.com,DIRECT
  - DOMAIN-SUFFIX,microsoft.com,DIRECT
  - DOMAIN-SUFFIX,microsoftonline.com,DIRECT
  - DOMAIN-SUFFIX,miui.com,DIRECT
  - DOMAIN-SUFFIX,miwifi.com,DIRECT
  - DOMAIN-SUFFIX,mob.com,DIRECT
  - DOMAIN-SUFFIX,netease.com,DIRECT
  - DOMAIN-SUFFIX,office.com,DIRECT
  - DOMAIN-SUFFIX,office365.com,DIRECT
  - DOMAIN-SUFFIX,oschina.net,DIRECT
  - DOMAIN-SUFFIX,ppsimg.com,DIRECT
  - DOMAIN-SUFFIX,pstatp.com,DIRECT
  - DOMAIN-SUFFIX,qcloud.com,DIRECT
  - DOMAIN-SUFFIX,qdaily.com,DIRECT
  - DOMAIN-SUFFIX,qdmm.com,DIRECT
  - DOMAIN-SUFFIX,qhimg.com,DIRECT
  - DOMAIN-SUFFIX,qhres.com,DIRECT
  - DOMAIN-SUFFIX,qidian.com,DIRECT
  - DOMAIN-SUFFIX,qihucdn.com,DIRECT
  - DOMAIN-SUFFIX,qiniu.com,DIRECT
  - DOMAIN-SUFFIX,qiniucdn.com,DIRECT
  - DOMAIN-SUFFIX,qiyipic.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,qqurl.com,DIRECT
  - DOMAIN-SUFFIX,rarbg.to,DIRECT
  - DOMAIN-SUFFIX,ruguoapp.com,DIRECT
  - DOMAIN-SUFFIX,segmentfault.com,DIRECT
  - DOMAIN-SUFFIX,sinaapp.com,DIRECT
  - DOMAIN-SUFFIX,smzdm.com,DIRECT
  - DOMAIN-SUFFIX,snapdrop.net,DIRECT
  - DOMAIN-SUFFIX,sogou.com,DIRECT
  - DOMAIN-SUFFIX,sogoucdn.com,DIRECT
  - DOMAIN-SUFFIX,sohu.com,DIRECT
  - DOMAIN-SUFFIX,soku.com,DIRECT
  - DOMAIN-SUFFIX,speedtest.net,DIRECT
  - DOMAIN-SUFFIX,sspai.com,DIRECT
  - DOMAIN-SUFFIX,suning.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,tencent.com,DIRECT
  - DOMAIN-SUFFIX,tenpay.com,DIRECT
  - DOMAIN-SUFFIX,tianyancha.com,DIRECT
  - DOMAIN-SUFFIX,tmall.com,DIRECT
  - DOMAIN-SUFFIX,tudou.com,DIRECT
  - DOMAIN-SUFFIX,umetrip.com,DIRECT
  - DOMAIN-SUFFIX,upaiyun.com,DIRECT
  - DOMAIN-SUFFIX,upyun.com,DIRECT
  - DOMAIN-SUFFIX,veryzhun.com,DIRECT
  - DOMAIN-SUFFIX,weather.com,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,xiami.com,DIRECT
  - DOMAIN-SUFFIX,xiami.net,DIRECT
  - DOMAIN-SUFFIX,xiaomicp.com,DIRECT
  - DOMAIN-SUFFIX,ximalaya.com,DIRECT
  - DOMAIN-SUFFIX,xmcdn.com,DIRECT
  - DOMAIN-SUFFIX,xunlei.com,DIRECT
  - DOMAIN-SUFFIX,yhd.com,DIRECT
  - DOMAIN-SUFFIX,yihaodianimg.com,DIRECT
  - DOMAIN-SUFFIX,yinxiang.com,DIRECT
  - DOMAIN-SUFFIX,ykimg.com,DIRECT
  - DOMAIN-SUFFIX,youdao.com,DIRECT
  - DOMAIN-SUFFIX,youku.com,DIRECT
  - DOMAIN-SUFFIX,zealer.com,DIRECT
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,zhimg.com,DIRECT
  - DOMAIN-SUFFIX,zimuzu.tv,DIRECT

  # China IP direct connection
  - GEOIP,CN,DIRECT

  # Other traffic goes through proxy
  - MATCH,🐟 Final 