---

log:
  level: "info"           
  format: "text"          
  output: "stdout"        
  file: "logs/anyproxy.log"
  max_size: 100           
  max_backups: 5          
  max_age: 30             
  compress: true          

proxy:
  socks5:
    listen_addr: ":1080"
    auth_username: ""
    auth_password: ""
  http:
    listen_addr: ":8080"
    auth_username: "user"
    auth_password: "password"

gateway:
  listen_addr: ":8443"
  tls_cert: "certs/server.crt"
  tls_key: "certs/server.key"
  auth_username: "gateway_user"
  auth_password: "gateway_password"

client:
  gateway_addr: "127.0.0.1:8443"
  gateway_tls_cert: "certs/server.crt"
  client_id: "client"
  replicas: 1
  auth_username: "gateway_user"
  auth_password: "gateway_password"
  forbidden_hosts:
    - "0.0.0.0"
    - "127.0.0.1"
    - "localhost"
    - "192.168.1.1"
    - "internal.example.com"
  allowed_hosts:
    - "example.com"
    - "example.org"
    - "example.net"
    - ".*"