---

log:
  level: "debug"
  format: "text"
  output: "stdout"
  file: "logs/anyproxy.log"
  max_size: 100           
  max_backups: 5          
  max_age: 30             
  compress: true          

gateway:
  listen_addr: ":9091"
  transport_type: "quic"
  tls_cert: "certs/server.crt"
  tls_key: "certs/server.key"
  auth_username: "gateway_user"
  auth_password: "gateway_password"
  proxy:
    socks5:
      listen_addr: ":1080"
    http:
      listen_addr: ":8080"
    tuic:
      listen_addr: ":9443"
  web:
    enabled: true
    listen_addr: ":8090"
    static_dir: "web/gateway/static"
    auth_enabled: true
    auth_username: "admin"
    auth_password: "admin123"
    session_key: "change-this-secret-key"

client:
  id: "client-id"
  group_id: "example-group"
  group_password: "password1"
  replicas: 3
  gateway:
    addr: "127.0.0.1:9091"
    transport_type: "quic"
    tls_cert: "certs/server.crt"
    auth_username: "gateway_user"
    auth_password: "gateway_password"
  forbidden_hosts:
    - "0.0.0.0"
    - "192.168.0.0/16"
    - "127.0.0.1"
  allowed_hosts:
    - "example.com"
    - "example.org"
    - "example.net"
    - ".*"
  open_ports:
    - remote_port: 8000
      protocol: "tcp"
      local_port: 3000
      local_host: "127.0.0.1"
    - remote_port: 8022
      protocol: "udp"
      local_port: 22
      local_host: "192.168.1.1"
  web:
    enabled: true
    listen_addr: ":8091"
    static_dir: "web/client/static"
    auth_enabled: true
    auth_username: "admin"
    auth_password: "admin123"
    session_key: "change-this-secret-key"
