---

log:
  level: "debug"
  format: "text"
  output: "stdout"
  file: "logs/anyproxy.log"
  max_size: 100           
  max_backups: 5          
  max_age: 30             
  compress: true          

client:
  id: "client-demo"
  gateway:
    addr: "47.107.181.88:8443"  # demo gateway address
    transport_type: "grpc"
    tls_cert: "certs/server.crt"
    auth_username: "gateway_user"
    auth_password: "gateway_password"
  # You must set group_id and group_password
  group_id: "demo-group"
  group_password: "demo-password"
  replicas: 1
  forbidden_hosts:
    - "0.0.0.0"
    - "127.0.0.1"
    - "192.168.0.0/16"
  allowed_hosts:
    - ".*"
  open_ports:
    # - remote_port: 8000
    #   protocol: "tcp"
    #   local_port: 3000
    #   local_host: "127.0.0.1"
  web:
    enabled: true
    listen_addr: ":8091"
    static_dir: "web/client/static"
    auth_enabled: true
    auth_username: "admin"
    auth_password: "admin123"
    session_key: "change-this-secret-key"